## numpy

In [1]:
import numpy as np

arr1 = np.array([1,2,3,4,5])

add = arr1 + 5
print(add)
sub = arr1 - 2
print(sub)
mul = arr1 * 3 
print(mul)
div = arr1 / 2
print(div)

[ 6  7  8  9 10]
[-1  0  1  2  3]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [5]:
f_element = arr1[0]
print(f_element)

l_element = arr1[-1]
print(l_element)

subst = arr1[1:4]
print(subst)

1
5
[2 3 4]


In [11]:
r_array = arr1.reshape((1, 5))
print("Reshaped array:\n", r_array)


transposed_matrix = r_array.T
print("Transposed matrix:\n", transposed_matrix)


Reshaped array:
 [[1 2 3 4 5]]
Transposed matrix:
 [[1]
 [2]
 [3]
 [4]
 [5]]


In [13]:
mean = np.mean(arr1)
median = np.median(arr1)
std_dev = np.std(arr1)
variance = np.var(arr1)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Variance:", variance)


Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951
Variance: 2.0


In [14]:
int_array = np.array([1, 2, 3], dtype=int)
float_array = np.array([1.1, 2.2, 3.3], dtype=float)
bool_array = np.array([True, False, True], dtype=bool)
str_array = np.array(['a', 'b', 'c'], dtype=str)

print("Integer array:", int_array)
print("Float array:", float_array)
print("Boolean array:", bool_array)
print("String array:", str_array)


Integer array: [1 2 3]
Float array: [1.1 2.2 3.3]
Boolean array: [ True False  True]
String array: ['a' 'b' 'c']


In [15]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

concatenated_array = np.concatenate((array1, array2))

print("Concatenated array:", concatenated_array)


Concatenated array: [1 2 3 4 5 6]


In [16]:
unsorted_array = np.array([3, 1, 2, 5, 4])

# Ascending order
sorted_array_asc = np.sort(unsorted_array)

# Descending order
sorted_array_desc = np.sort(unsorted_array)[::-1]

print("Sorted array (ascending):", sorted_array_asc)
print("Sorted array (descending):", sorted_array_desc)


Sorted array (ascending): [1 2 3 4 5]
Sorted array (descending): [5 4 3 2 1]


## pandas

In [17]:
import pandas as pd

# Load data from a CSV file
df_csv = pd.read_csv('student data.csv')


In [18]:
# Get the shape of the DataFrame
print(df_csv.shape)


(50, 5)


In [19]:
# Get the data types of each column
print(df_csv.dtypes)


roll no       int64
Name         object
Chemistry     int64
Physics       int64
Math          int64
dtype: object


In [22]:
# Check for missing values
print(df_csv.isnull().sum())


roll no      0
Name         0
Chemistry    0
Physics      0
Math         0
dtype: int64


In [23]:
# Get descriptive statistics
print(df_csv.describe())


         roll no  Chemistry    Physics       Math
count   50.00000  50.000000  50.000000  50.000000
mean   125.50000  68.420000  65.060000  77.360000
std     14.57738  14.116266  22.676437  14.789351
min    101.00000  45.000000  23.000000  45.000000
25%    113.25000  56.250000  47.500000  71.250000
50%    125.50000  68.500000  73.500000  79.000000
75%    137.75000  80.750000  82.750000  88.750000
max    150.00000  92.000000  92.000000  98.000000


In [26]:
# Select specific columns
selected_columns = df_csv[['roll no', 'Math']]
print(selected_columns)

    roll no  Math
0       101    87
1       102    88
2       103    89
3       104    90
4       105    67
5       106    68
6       107    69
7       108    70
8       109    71
9       110    72
10      111    73
11      112    74
12      113    75
13      114    76
14      115    77
15      116    78
16      117    79
17      118    80
18      119    81
19      120    82
20      121    83
21      122    84
22      123    85
23      124    86
24      125    87
25      126    88
26      127    89
27      128    90
28      129    91
29      130    92
30      131    93
31      132    94
32      133    95
33      134    96
34      135    97
35      136    98
36      137    78
37      138    45
38      139    46
39      140    89
40      141    78
41      142    56
42      143    78
43      144    54
44      145    78
45      146    46
46      147    79
47      148    46
48      149    45
49      150    56


In [28]:
# Filter rows where column1 is greater than a certain value
filtered_rows = df_csv[df_csv['Math'] > 92]
print(filtered_rows)

    roll no     Name  Chemistry  Physics  Math
30      131    Wajid         74       88    93
31      132   Waseeb         75       89    94
32      133    Shiza         76       90    95
33      134  Shabina         77       91    96
34      135  Shazain         78       55    97
35      136    Lubna         79       61    98
